version: '3.1'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: relaywriter_db
    ports:
      - "5432:5432"
    volumes:
      - /db-data:/var/lib/postgresql/data

#  relay-writer-api:
#    build: .
#    image: relay-writer
#    depends_on:
#      - postgres
#    hostname: localhost
#    restart: always
#    ports:
#      - "8080:8080"


volumes:
  data-volume: